# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Optimizing Joy
email: optimizingjoy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a site about optimization, happiness and joy (mostly). It ends up being posts of things
  I find beneficial to the human experience, yet another personal blog on the web. However, I try not
  to give my opinions, I may point to the opinions of others but mostly to research. enJOY. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.optimizingjoy.com" # the base hostname & protocol for your site
twitter_username: I don't tweet
github_username:  nunya

# Build settings
markdown: kramdown
